Тема "Вычисления с помощью Numpy"

Задание 1

Импортируйте библиотеку Numpy и дайте ей псевдоним np.

In [2]:
import numpy as np

Создайте массив Numpy под названием "a" размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7.

In [3]:
a = np.array([[1,6], 
              [2,8], 
              [3,11], 
              [3,10], 
              [1,7]], dtype=int)
print(a)
print('Форма a: {}'.format(a.shape))

[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Форма a: (5, 2)


Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy.

In [4]:
print('Среднее значение по каждому признаку: {}'.format(a.mean(axis=0)))

Среднее значение по каждому признаку: [2.  8.4]


Результат записать в массив "mean_a", в нем должно быть 2 элемента.

In [5]:
mean_a = a.mean(axis=0).copy()

In [6]:
print(mean_a)

[2.  8.4]


Задание 2

Вычислите массив "a_centered", отняв от значений массива "а" средние значения соответствующих признаков, содержащиеся в массиве "mean_a". Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [7]:
print('Массив a: ')
print(a)

print('Массив mean_a: ')
print(mean_a)

Массив a: 
[[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]
Массив mean_a: 
[2.  8.4]


In [8]:
a_centered = a - mean_a
print('Массив a_centered: ')
print(a_centered)

Массив a_centered: 
[[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


Задание 3

Найдите скалярное произведение столбцов массива "a_centered". В результате должна получиться величина "a_centered_sp".

In [9]:
j1 = a_centered[:, :1].copy()
print(j1)
j1_t = j1.T

[[-1.]
 [ 0.]
 [ 1.]
 [ 1.]
 [-1.]]


In [10]:
j2 = a_centered[:, 1:].copy()
print(j2)

[[-2.4]
 [-0.4]
 [ 2.6]
 [ 1.6]
 [-1.4]]


In [11]:
a_centered_sp = j1_t.dot(j2)[0, 0]
print(a_centered_sp)

8.0


Затем поделите "a_centered_sp" на N-1, где N - число наблюдений.

In [12]:
N = 5
cov_res = a_centered_sp/(N-1)
print(cov_res)

2.0


Задание 4**

В этом задании проверьте получившееся число, вычислив ковариацию еще одним способом - с помощью функции np.cov. В качестве аргумента m функция np.cov должна принимать транспонированный массив "a". В получившейся ковариационной матрице искомое значение ковариации будет равно элементу в строке с индексом 0 и столбце с индексом 1.


In [13]:
a_t = a.T
print(a_t)

[[ 1  2  3  3  1]
 [ 6  8 11 10  7]]


In [14]:
cov_matrix = np.cov(a_t)
print(cov_matrix)

[[1.  2. ]
 [2.  4.3]]


In [15]:
cov_res = cov_matrix[0, 1]
print(cov_res)

2.0


Тема "Работа с данными в Pandas"

Задание 1

Импортируйте библиотеку Pandas и дайте ей псевдоним pd. Создайте датафрейм "authors" со столбцами "author_id" и "author_name", в которых соответственно содержатся данные: [1, 2, 3] и ['Тургенев', 'Чехов', 'Островский'].

In [16]:
import pandas as pd

In [17]:
a = {
    "author_id": [1, 2, 3],
    "author_name": ['Тургенев', 'Чехов', 'Островский']
}
authors = pd.DataFrame(a)
print(authors)

   author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский


Затем создайте датафрейм "book" cо столбцами "author_id", "book_title" и "price", в которых соответственно содержатся данные:  
[1, 1, 1, 2, 2, 3, 3], 
['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
[450, 300, 350, 500, 450, 370, 290].


In [18]:
b = {
    "author_id": [1, 1, 1, 2, 2, 3, 3],
    "book_title": ['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'], 
    "price": [450, 300, 350, 500, 450, 370, 290]
}
book = pd.DataFrame(b)
print(book)

   author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290


Задание 2

Получите датафрейм "authors_price", соединив датафреймы "authors" и "books" по полю "author_id".

In [19]:
authors_price = pd.merge(authors, book, on='author_id', how='inner')
print(authors_price)

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


Задание 3

Создайте датафрейм "top5", в котором содержатся строки из "authors_price" с пятью самыми дорогими книгами.

In [20]:
top5 = authors_price.nlargest(5, "price")
print(top5)

   author_id author_name         book_title  price
3          2       Чехов   Толстый и тонкий    500
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
5          3  Островский              Гроза    370
2          1    Тургенев  Дворянское гнездо    350


Задание 4

Создайте датафрейм "authors_stat" на основе информации из "authors_price". В датафрейме "authors_stat" должны быть четыре столбца:
"author_name", "min_price", "max_price" и "mean_price", в которых должны содержаться соответственно имя автора, минимальная, максимальная и средняя цена на книги этого автора.


In [21]:
authors_price.sort_values(by="author_name", inplace=True)
authors_price

author_id author_name            book_title  price
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450

In [22]:
groupby = authors_price.groupby("author_name")

In [23]:
col2 = groupby["price"].min()
col2

author_name
Островский    290
Тургенев      300
Чехов         450
Name: price, dtype: int64

In [24]:
col3 = groupby["price"].max()
col3

author_name
Островский    370
Тургенев      450
Чехов         500
Name: price, dtype: int64

In [25]:
col4 = groupby["price"].mean()
col4

author_name
Островский    330.000000
Тургенев      366.666667
Чехов         475.000000
Name: price, dtype: float64

In [26]:
c = {
    "author_name": authors_price["author_name"].unique(),
    "min_price": col2.values,
    "max_price": col3.values,
    "mean_price": col4.values
}
authors_stat = pd.DataFrame(c)
print(authors_stat)

  author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000


Задание 5**

Создайте новый столбец в датафрейме "authors_price" под названием "cover", в нем будут располагаться данные о том, какая обложка у данной книги - твердая или мягкая. В этот столбец поместите данные из следующего списка:
['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая'].


In [28]:
authors_price.sort_values(by="author_id", inplace=True)
print(authors_price)

   author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290


In [29]:
authors_price["cover"] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']
print(authors_price)

   author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая


Для каждого автора посчитайте суммарную стоимость книг в твердой и мягкой обложке. Используйте для этого функцию pd.pivot_table. При этом столбцы должны называться "твердая" и "мягкая", а индексами должны быть фамилии авторов. Пропущенные значения стоимостей заполните нулями, при необходимости загрузите библиотеку Numpy.


In [36]:
book_info = authors_price.pivot_table(index="author_name", columns="cover", values="price", aggfunc=np.sum, fill_value=0)
book_info

cover        мягкая  твердая
author_name                 
Островский      660        0
Тургенев        650      450
Чехов             0      950

Назовите полученный датасет "book_info" и сохраните его в формат pickle под названием "book_info.pkl". Затем загрузите из этого файла датафрейм и назовите его "book_info2". Удостоверьтесь, что датафреймы "book_info" и "book_info2" идентичны.


In [37]:
book_info.to_pickle("book_info.pkl")

In [38]:
book_info2 = pd.read_pickle("book_info.pkl")

In [43]:
book_info == book_info2

cover        мягкая  твердая
author_name                 
Островский     True     True
Тургенев       True     True
Чехов          True     True

Конец